CREATE USER ionut WITH ENCRYPTED PASSWORD '77777';
GRANT ALL PRIVILEGES ON DATABASE d4kj1fd7b9k6n7 TO ionut ;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ionut;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ionut;